package com.letme.Users.entity;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlRootElement;


/**
 * Created by mbajwa11 on 12/22/16.
 */
@Table(name = "users_info")
@Entity
public class UsersInfo{
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    @NotNull
    @Column(name = "user_id")
    private Integer user_id;

    @Column(name = "street_add")
    private String street_add;

    @Column(name = "city")
    private String city;

    @Column(name = "state")
    private String state;

    @Override
    public String toString() {
        return "UsersInfo{" +
                "id=" + id +
                ", user_id=" + user_id +
                ", street_add='" + street_add + '\'' +
                ", city='" + city + '\'' +
                ", state='" + state + '\'' +
                ", zip='" + zip + '\'' +
                ", country='" + country + '\'' +
                ", verified=" + verified +
                ", fb_verified=" + fb_verified +
                ", google_verified=" + google_verified +
                '}';
    }

    @Column(name = "zip")
    private String zip;

    @Column(name = "country")
    private String country;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    public String getStreet_add() {
        return street_add;
    }

    public void setStreet_add(String street_add) {
        this.street_add = street_add;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getZip() {
        return zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public boolean isVerified() {
        return verified;
    }

    public void setVerified(boolean verified) {
        this.verified = verified;
    }

    public boolean isFb_verified() {
        return fb_verified;
    }

    public void setFb_verified(boolean fb_verified) {
        this.fb_verified = fb_verified;
    }

    public boolean isGoogle_verified() {
        return google_verified;
    }

    public void setGoogle_verified(boolean google_verified) {
        this.google_verified = google_verified;
    }

    @Column(name = "verified")
    private boolean verified;

    @Column(name = "fb_verified")
    private boolean fb_verified;

    @Column(name = "google_verified")
    private boolean google_verified;
}
